---
exp_name: GRAN
exp_dir: exp/GRAN
runner: GranRunner
use_horovod: false
use_gpu: true
device: cuda
gpus: [0]
seed: 4454
dataset:
  loader_name: GRANData
  name: TWITCH
  data_path: # ../data
  node_order: DFS # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 1 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: false
  is_save_split: false
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  is_overwrite_precompute: false
model:
  name: GRANMixtureBernoulli
  num_mix_component: 20
  is_sym: true
  block_size: 1
  sample_stride: 1
  max_num_nodes: 550
  hidden_dim: 512
  embedding_dim: 512
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0
train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_epoch: [500] # no decay
  num_workers: 0
  max_epoch: 30000
  batch_size: 50
  display_iter: 10
  snapshot_epoch: 200
  valid_epoch: 10
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch:
  resume_dir: # ../exp/GRAN/X
  resume_model: # model_snapshot_0030000.pth
test:
  batch_size: 1
  num_workers: 12
  num_test_gen: 12 # number of generated samples
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  num_vis: 12
  vis_num_row: 4 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: # ../exp/GRAN/X
  test_model_name: model_snapshot_0030000.pth
generate:
  batch_size: 1
  num_workers: 12
  num_test_gen: 4 # number of generated samples
  is_eval: true
  is_eval_rmat: true
  is_vis: true
  is_single_plot: true # visualize `num_vis` samples in a single image
  num_vis: 12
  vis_num_row: 4 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: # ../exp/GRAN/X
  test_model_name: model_snapshot_0030000.pth
